#! /usr/bin/env escript
-module(make).
-export([main/1]).

main(_) ->
    true = code:add_patha("ebin"),
    Modules = make:all(),
    ok = io:format("~p~n", [Modules]),
    ok = io:format("Writing docs...~n"),
    ok = edoc:application(zuuid, ".", []).
